"use client";

import { ModalManager, ThemeProvider } from "postshape";
import "postshape/dist/style.css";
import Desktop from "./desktop";
import { Media, MediaContextProvider } from "./media";
import Mobile from "./mobile";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ModalManager>
            <MediaContextProvider>
              <Media lessThan="sm">
                <Mobile children={children} />
              </Media>
              <Media greaterThanOrEqual="sm">
                <Desktop children={children} />
              </Media>
            </MediaContextProvider>
          </ModalManager>
        </ThemeProvider>
      </body>
    </html>
  );
}
