name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install Dependencies"
        run: yarn
      - name: "Build package"
        run: yarn workspace postshape build
      - name: "Linting"
        run: yarn lint
      - name: "Build site"
        run: yarn workspace site build
      - name: "Publish package"
        run: yarn deploy:lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: 'Deploy site'
      #   run: 'yarn deploy:site --token ${{ secrets.FIREBASE_TOKEN }}'
